version: "3"
services:
  app:
    image: codeshaurya9/tictac:latest    
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: yarn start